-- Shopping Cart Resources --
GET /shopping-cart/in/ur/github
< 200
{ "items": [
  { "url": "/shopping-cart/socks" "product":"!11!!11!!", "quantity": 1, "name": "Shiny new socks", "price": 1.25 }
] }

